puts "Cleaning campus database..."
School.destroy_all

puts "Cleaning users database..."
User.destroy_all

puts "Creating schools..."
lisbon = School.create(city: "Lisbon", country: "Portugal", address: "Rua do Conde de Redondo 91B, 1150-103 Lisboa")
puts "#{lisbon.city} school created!"


puts "Creating users..."
user1 = User.create(email: "miguelpfigueiredo@gmail.com", password: "lw2022lisbon")
user2 = User.create(email: "pedro.agostinho@lewagon.org", password: "lw2022lisbon")
puts "Users created!"

puts "Creating association of users and schools..."
UserSchool.create(user_id: user1.id, school_id: lisbon.id)
UserSchool.create(user_id: user2.id, school_id: lisbon.id)

puts "Do you want to recreate the bootcamps_weeks table? [y/n]"
puts "(you will lose all the information regarding teachers experience and need to reupdate the roaster)"
answer = gets.chomp

if ["y", "yes"].include?(answer.downcase)
    
  puts "Cleaning bootcamps_weeks database..."
  BootcampsWeek.destroy_all

  puts "Creating WEB bootcamps_weeks..."
  BootcampsWeek.create(week: 1, course_slug: "web", lecture_day_slug: "00-Setup", topic: "Setup")
  BootcampsWeek.create(week: 1, course_slug: "web", lecture_day_slug: "01-Ruby/01-Programming-basics", topic: "Ruby")
  BootcampsWeek.create(week: 1, course_slug: "web", lecture_day_slug: "01-Ruby/02-Flow-Array", topic: "Ruby")
  BootcampsWeek.create(week: 1, course_slug: "web", lecture_day_slug: "01-Ruby/03-Iterators-Blocks", topic: "Ruby")
  BootcampsWeek.create(week: 1, course_slug: "web", lecture_day_slug: "01-Ruby/04-Hash-Symbols", topic: "Ruby")
  BootcampsWeek.create(week: 2, course_slug: "web", lecture_day_slug: "01-Ruby/05-Regular-Expressions", topic: "Reboot")
  BootcampsWeek.create(week: 2, course_slug: "web", lecture_day_slug: "01-Ruby/06-Parsing", topic: "Reboot")
  BootcampsWeek.create(week: 2, course_slug: "web", lecture_day_slug: "02-OOP/01-OO-Basics", topic: "OOP")
  BootcampsWeek.create(week: 2, course_slug: "web", lecture_day_slug: "02-OOP/02-OO-Advanced", topic: "OOP")
  BootcampsWeek.create(week: 2, course_slug: "web", lecture_day_slug: "02-OOP/03-Cookbook-Day-One", topic: "Building-Software")
  BootcampsWeek.create(week: 3, course_slug: "web", lecture_day_slug: "02-OOP/04-Cookbook-Day-Two", topic: "Building-Software")
  BootcampsWeek.create(week: 3, course_slug: "web", lecture_day_slug: "02-OOP/05-Food-Delivery-Day-One", topic: "Building-Software")
  BootcampsWeek.create(week: 3, course_slug: "web", lecture_day_slug: "02-OOP/06-Food-Delivery-Day-Two", topic: "Building-Software")
  BootcampsWeek.create(week: 3, course_slug: "web", lecture_day_slug: "03-AR-Database/01-DB-Design-and-SQL", topic: "AR-Database")
  BootcampsWeek.create(week: 3, course_slug: "web", lecture_day_slug: "03-AR-Database/02-SQL-CRUD", topic: "AR-Database")
  BootcampsWeek.create(week: 4, course_slug: "web", lecture_day_slug: "03-AR-Database/03-ActiveRecord-Basics", topic: "AR-Database")
  BootcampsWeek.create(week: 4, course_slug: "web", lecture_day_slug: "03-AR-Database/04-ActiveRecord-Advanced", topic: "AR-Database")
  BootcampsWeek.create(week: 4, course_slug: "web", lecture_day_slug: "04-Front-End/01-HTML-and-CSS", topic: "HTML-CSS")
  BootcampsWeek.create(week: 4, course_slug: "web", lecture_day_slug: "04-Front-End/02-CSS-components", topic: "HTML-CSS")
  BootcampsWeek.create(week: 4, course_slug: "web", lecture_day_slug: "04-Front-End/03-Bootstrap", topic: "HTML-CSS")
  BootcampsWeek.create(week: 5, course_slug: "web", lecture_day_slug: "04-Front-End/04-JavaScript-basics", topic: "JS")
  BootcampsWeek.create(week: 5, course_slug: "web", lecture_day_slug: "04-Front-End/04-Middleman", topic: "JS")
  BootcampsWeek.create(week: 5, course_slug: "web", lecture_day_slug: "04-Front-End/05-DOM-and-Events", topic: "JS")
  BootcampsWeek.create(week: 5, course_slug: "web", lecture_day_slug: "04-Front-End/05-JavaScript-DOM", topic: "JS")
  BootcampsWeek.create(week: 5, course_slug: "web", lecture_day_slug: "04-Front-End/05-Javascript-and-jQuery", topic: "JS")
  BootcampsWeek.create(week: 5, course_slug: "web", lecture_day_slug: "04-Front-End/06-HTTP-and-AJAX", topic: "JS")
  BootcampsWeek.create(week: 5, course_slug: "web", lecture_day_slug: "04-Front-End/06-Events-And-AJAX", topic: "JS")
  BootcampsWeek.create(week: 5, course_slug: "web", lecture_day_slug: "04-Front-End/06-Events-And-Plugins", topic: "JS")
  BootcampsWeek.create(week: 5, course_slug: "web", lecture_day_slug: "04-Front-End/07-JavaScript-Plugins", topic: "JS")
  BootcampsWeek.create(week: 5, course_slug: "web", lecture_day_slug: "04-Front-End/07-JavaScript-Tooling", topic: "JS")
  BootcampsWeek.create(week: 5, course_slug: "web", lecture_day_slug: "04-Front-End/07-HTTP-and-Ajax", topic: "JS")
  BootcampsWeek.create(week: 5, course_slug: "web", lecture_day_slug: "04-Front-End/08-Product-Design-Sprint", topic: "Product-Design")
  BootcampsWeek.create(week: 6, course_slug: "web", lecture_day_slug: "05-Rails/01-Rails-intro", topic: "Rails")
  BootcampsWeek.create(week: 6, course_slug: "web", lecture_day_slug: "05-Rails/02-Rails-CRUD", topic: "Rails")
  BootcampsWeek.create(week: 6, course_slug: "web", lecture_day_slug: "05-Rails/03-Rails-restaurant-reviews", topic: "Rails")
  BootcampsWeek.create(week: 6, course_slug: "web", lecture_day_slug: "05-Rails/04-Rails-mister-cocktail", topic: "Rails")
  BootcampsWeek.create(week: 6, course_slug: "web", lecture_day_slug: "05-Rails/05-Rails-MC-with-images", topic: "Rails")
  BootcampsWeek.create(week: 7, course_slug: "web", lecture_day_slug: "05-Rails/06-Airbnb-Devise", topic: "Airbnb")
  BootcampsWeek.create(week: 7, course_slug: "web", lecture_day_slug: "05-Rails/07-Airbnb-Facebook-connect", topic: "Airbnb")
  BootcampsWeek.create(week: 7, course_slug: "web", lecture_day_slug: "05-Rails/08-Airbnb-Geocoder", topic: "Airbnb")
  BootcampsWeek.create(week: 7, course_slug: "web", lecture_day_slug: "05-Rails/09-Airbnb-SMTP", topic: "Airbnb")
  BootcampsWeek.create(week: 7, course_slug: "web", lecture_day_slug: "05-Rails/10-Airbnb-Ajax-in-Rails", topic: "Airbnb")
  BootcampsWeek.create(week: 8, course_slug: "web", lecture_day_slug: "06-Projects/01-Pundit", topic: "Projects")
  BootcampsWeek.create(week: 8, course_slug: "web", lecture_day_slug: "06-Projects/02-i18n", topic: "Projects")
  BootcampsWeek.create(week: 8, course_slug: "web", lecture_day_slug: "06-Projects/03-Advanced-Admin", topic: "Projects")
  BootcampsWeek.create(week: 8, course_slug: "web", lecture_day_slug: "06-Projects/04-Background-jobs", topic: "Projects")
  BootcampsWeek.create(week: 8, course_slug: "web", lecture_day_slug: "06-Projects/05-Build-an-API", topic: "Projects")
  BootcampsWeek.create(week: 9, course_slug: "web", lecture_day_slug: "06-Projects/06-Payment-with-Stripe", topic: "Projects")
  BootcampsWeek.create(week: 9, course_slug: "web", lecture_day_slug: "06-Projects/07-Search", topic: "Projects")
  BootcampsWeek.create(week: 9, course_slug: "web", lecture_day_slug: "06-Projects/08-Testing", topic: "Projects")
  BootcampsWeek.create(week: 9, course_slug: "web", lecture_day_slug: "06-Projects/09-Dress-Rehearsal-React", topic: "Projects")
  BootcampsWeek.create(week: 9, course_slug: "web", lecture_day_slug: "06-Projects/10-Demo-Day", topic: "Projects")
  
  puts "WEB bootcamps_weeks created!"
  
  puts "Creating DATA bootcamps_weeks..."
  BootcampsWeek.create(week: 1, course_slug: "data", lecture_day_slug: "00-Setup", topic: "Setup")
  BootcampsWeek.create(week: 1, course_slug: "data", lecture_day_slug: "01-Python/01-Programming-Basics", topic: "Python")
  BootcampsWeek.create(week: 1, course_slug: "data", lecture_day_slug: "01-Python/02-Data-Sourcing", topic: "Python")
  BootcampsWeek.create(week: 1, course_slug: "data", lecture_day_slug: "01-Python/03-SQL-Basics", topic: "Python")
  BootcampsWeek.create(week: 1, course_slug: "data", lecture_day_slug: "01-Python/04-SQL-Advanced", topic: "Python")
  BootcampsWeek.create(week: 2, course_slug: "data", lecture_day_slug: "02-Data-Toolkit/01-Data-Analysis", topic: "Data Toolkit")
  BootcampsWeek.create(week: 2, course_slug: "data", lecture_day_slug: "02-Data-Toolkit/02-Data-Sourcing", topic: "Data Toolkit")
  BootcampsWeek.create(week: 2, course_slug: "data", lecture_day_slug: "02-Data-Toolkit/03-Data-Visualization", topic: "Data Toolkit")
  BootcampsWeek.create(week: 2, course_slug: "data", lecture_day_slug: "03-Maths/01-Algebra-Calculus", topic: "Maths")
  BootcampsWeek.create(week: 2, course_slug: "data", lecture_day_slug: "03-Maths/01", topic: "Maths")
  BootcampsWeek.create(week: 2, course_slug: "data", lecture_day_slug: "03-Maths/02-Statistics-Probabilities", topic: "Maths")
  BootcampsWeek.create(week: 3, course_slug: "data", lecture_day_slug: "04-Decision-Science/01-Project-Setup", topic: "Decision Science")
  BootcampsWeek.create(week: 3, course_slug: "data", lecture_day_slug: "04-Decision-Science/02-Statistical-Inference", topic: "Decision Science")
  BootcampsWeek.create(week: 3, course_slug: "data", lecture_day_slug: "04-Decision-Science/03-Linear-Regression", topic: "Decision Science")
  BootcampsWeek.create(week: 3, course_slug: "data", lecture_day_slug: "04-Decision-Science/04-Logistic-Regression", topic: "Decision Science")
  BootcampsWeek.create(week: 3, course_slug: "data", lecture_day_slug: "04-Decision-Science/05-Communicate", topic: "Decision Science")
  BootcampsWeek.create(week: 4, course_slug: "data", lecture_day_slug: "05-ML/01-Fundamentals-of-Machine-Learning", topic: "Machine Learning")
  BootcampsWeek.create(week: 4, course_slug: "data", lecture_day_slug: "05-ML/02-Prepare-the-dataset", topic: "Machine Learning")
  BootcampsWeek.create(week: 4, course_slug: "data", lecture_day_slug: "05-ML/03-Performance-metrics", topic: "Machine Learning")
  BootcampsWeek.create(week: 4, course_slug: "data", lecture_day_slug: "05-ML/04-Under-the-hood", topic: "Machine Learning")
  BootcampsWeek.create(week: 4, course_slug: "data", lecture_day_slug: "05-ML/05-Model-Tuning", topic: "Machine Learning")
  BootcampsWeek.create(week: 5, course_slug: "data", lecture_day_slug: "05-ML/08-Workflow", topic: "Machine Learning")
  BootcampsWeek.create(week: 5, course_slug: "data", lecture_day_slug: "05-ML/07-Ensemble-Methods", topic: "Machine Learning")
  BootcampsWeek.create(week: 5, course_slug: "data", lecture_day_slug: "05-ML/06-Unsupervised-Learning", topic: "Machine Learning")
  BootcampsWeek.create(week: 5, course_slug: "data", lecture_day_slug: "05-ML/09-Time-Series", topic: "Machine Learning")
  BootcampsWeek.create(week: 5, course_slug: "data", lecture_day_slug: "05-ML/09-Vision", topic: "Machine Learning")
  BootcampsWeek.create(week: 5, course_slug: "data", lecture_day_slug: "05-ML/10-Natural-Language-Processing", topic: "Machine Learning")
  BootcampsWeek.create(week: 6, course_slug: "data", lecture_day_slug: "06-Deep-Learning/01-Fundamentals-of-Deep-Learning", topic: "Deep Learning")
  BootcampsWeek.create(week: 6, course_slug: "data", lecture_day_slug: "06-Deep-Learning/01", topic: "Deep Learning")
  BootcampsWeek.create(week: 6, course_slug: "data", lecture_day_slug: "06-Deep-Learning/02-Optimizer-loss-and-fitting", topic: "Deep Learning")
  BootcampsWeek.create(week: 6, course_slug: "data", lecture_day_slug: "06-Deep-Learning/02", topic: "Deep Learning")
  BootcampsWeek.create(week: 6, course_slug: "data", lecture_day_slug: "06-Deep-Learning/03-Convolutional-Neural-Networks", topic: "Deep Learning")
  BootcampsWeek.create(week: 6, course_slug: "data", lecture_day_slug: "06-Deep-Learning/03", topic: "Deep Learning")
  BootcampsWeek.create(week: 6, course_slug: "data", lecture_day_slug: "06-Deep-Learning/04-Recurrent-Neural-Networks", topic: "Deep Learning")
  BootcampsWeek.create(week: 6, course_slug: "data", lecture_day_slug: "06-Deep-Learning/04", topic: "Deep Learning")
  BootcampsWeek.create(week: 6, course_slug: "data", lecture_day_slug: "06-Deep-Learning/05-Natural-Language-Processing", topic: "Deep Learning")
  BootcampsWeek.create(week: 6, course_slug: "data", lecture_day_slug: "06-Deep-Learning/05", topic: "Deep Learning")
  BootcampsWeek.create(week: 7, course_slug: "data", lecture_day_slug: "07-ML-Ops/01-Train-at-scale", topic: "ML Ops")
  BootcampsWeek.create(week: 7, course_slug: "data", lecture_day_slug: "07-Data-Engineering/01-Code-as-a-Product", topic: "ML Ops")
  BootcampsWeek.create(week: 7, course_slug: "data", lecture_day_slug: "07-ML-Ops/02-Cloud-training", topic: "ML Ops")
  BootcampsWeek.create(week: 7, course_slug: "data", lecture_day_slug: "07-Data-Engineering/02-ML-Iteration", topic: "ML Ops")
  BootcampsWeek.create(week: 7, course_slug: "data", lecture_day_slug: "07-Data-Engineering/02-ML-Pipelines", topic: "ML Ops")
  BootcampsWeek.create(week: 7, course_slug: "data", lecture_day_slug: "07-ML-Ops/03-Automate-model-lifecycle", topic: "ML Ops")
  BootcampsWeek.create(week: 7, course_slug: "data", lecture_day_slug: "07-Data-Engineering/03-ML-Iteration", topic: "ML Ops")
  BootcampsWeek.create(week: 7, course_slug: "data", lecture_day_slug: "07-Data-Engineering/03-Train-at-scale", topic: "ML Ops")
  BootcampsWeek.create(week: 7, course_slug: "data", lecture_day_slug: "07-ML-Ops/04-Predict-in-production", topic: "ML Ops")
  BootcampsWeek.create(week: 7, course_slug: "data", lecture_day_slug: "07-Data-Engineering/04-Train-at-scale", topic: "ML Ops")
  BootcampsWeek.create(week: 7, course_slug: "data", lecture_day_slug: "07-Data-Engineering/04-Predict-in-production", topic: "ML Ops")
  BootcampsWeek.create(week: 7, course_slug: "data", lecture_day_slug: "07-ML-Ops/05-User-interface", topic: "ML Ops")
  BootcampsWeek.create(week: 7, course_slug: "data", lecture_day_slug: "07-Data-Engineering/05-Predict", topic: "ML Ops")
  BootcampsWeek.create(week: 7, course_slug: "data", lecture_day_slug: "07-Data-Engineering/05-User-interface", topic: "ML Ops")
  BootcampsWeek.create(week: 8, course_slug: "data", lecture_day_slug: "08-Projects/01", topic: "Projects")
  BootcampsWeek.create(week: 8, course_slug: "data", lecture_day_slug: "08-Projects/02", topic: "Projects")
  BootcampsWeek.create(week: 8, course_slug: "data", lecture_day_slug: "08-Projects/03", topic: "Projects")
  BootcampsWeek.create(week: 8, course_slug: "data", lecture_day_slug: "08-Projects/04", topic: "Projects")
  BootcampsWeek.create(week: 8, course_slug: "data", lecture_day_slug: "08-Projects/05", topic: "Projects")
  BootcampsWeek.create(week: 9, course_slug: "data", lecture_day_slug: "08-Projects/06", topic: "Projects")
  BootcampsWeek.create(week: 9, course_slug: "data", lecture_day_slug: "08-Projects/07", topic: "Projects")
  BootcampsWeek.create(week: 9, course_slug: "data", lecture_day_slug: "08-Projects/08", topic: "Projects")
  BootcampsWeek.create(week: 9, course_slug: "data", lecture_day_slug: "08-Projects/09", topic: "Projects")
  BootcampsWeek.create(week: 9, course_slug: "data", lecture_day_slug: "08-Projects/10-Demo-Day", topic: "Projects")
  
  puts "DATA bootcamps_weeks created!"
  
  puts "Creating OTHER bootcamps_weeks..."
  BootcampsWeek.create(week: 10, course_slug: "career", lecture_day_slug: "career/interview-preparation-being-the-star-candidate")
  BootcampsWeek.create(week: 10, course_slug: "career", lecture_day_slug: "career/job-applications-networking")
  BootcampsWeek.create(week: 10, course_slug: "career", lecture_day_slug: "career/personal-profile")
  
  BootcampsWeek.create(week: nil, course_slug: "python_for_finance_2", lecture_day_slug: "python/data-manipulation")
  BootcampsWeek.create(week: nil, course_slug: "python_for_finance_2", lecture_day_slug: "python/data-visualization")

end

puts "Do you want to delete the teachers table? [y/n]"
puts "(you will lose all the teachers info that is not on the seeds. Update seeds with all teachers github_nickname's if you want to run db:seed and not lose information)"
answer = gets.chomp

if ["y", "yes"].include?(answer.downcase)
  puts "Cleaning teachers database..."
  puts "Creating baseline teachers table..."
  Teacher.destroy_all

  puts "Creating WEB teachers..."
  Teacher.create(github_nickname: "jbernardoviana", school_id: lisbon.id)
  Teacher.create(github_nickname: "apires89", school_id: lisbon.id)
  Teacher.create(github_nickname: "joaosanches1990", school_id: lisbon.id)
  Teacher.create(github_nickname: "syrashid", school_id: lisbon.id)
  Teacher.create(github_nickname: "rikas", school_id: lisbon.id)
  Teacher.create(github_nickname: "Gittelo", school_id: lisbon.id)
  Teacher.create(github_nickname: "nmajor", school_id: lisbon.id)
  Teacher.create(github_nickname: "rahulkeerthi", school_id: lisbon.id)
  Teacher.create(github_nickname: "carlosmendes", school_id: lisbon.id)
  Teacher.create(github_nickname: "rodrigoruas", school_id: lisbon.id)
  Teacher.create(github_nickname: "gabrielecanepa", school_id: lisbon.id)
  Teacher.create(github_nickname: "margaridatoureiro", school_id: lisbon.id)
  Teacher.create(github_nickname: "patricknpinto", school_id: lisbon.id)
  Teacher.create(github_nickname: "todd-sn", school_id: lisbon.id)
  Teacher.create(github_nickname: "dmcarmo", school_id: lisbon.id)
  Teacher.create(github_nickname: "franciscoovazevedo", school_id: lisbon.id)
  Teacher.create(github_nickname: "barbaraperic", school_id: lisbon.id)
  Teacher.create(github_nickname: "monicanabais", school_id: lisbon.id)
  Teacher.create(github_nickname: "arieivs", school_id: lisbon.id)
  Teacher.create(github_nickname: "zoe-gld", school_id: lisbon.id)
  Teacher.create(github_nickname: "AlexdrFontes", school_id: lisbon.id)
  Teacher.create(github_nickname: "sians", school_id: lisbon.id)
  Teacher.create(github_nickname: "RitaLaia", school_id: lisbon.id)
  Teacher.create(github_nickname: "ruivitorbaltazar", school_id: lisbon.id)
  Teacher.create(github_nickname: "alexterenda", school_id: lisbon.id)
  Teacher.create(github_nickname: "susannapezzini", school_id: lisbon.id)
  Teacher.create(github_nickname: "beatriznbarroso", school_id: lisbon.id)
  Teacher.create(github_nickname: "henrialb", school_id: lisbon.id)
  Teacher.create(github_nickname: "tpinto", school_id: lisbon.id)
  Teacher.create(github_nickname: "G-Souza-99", school_id: lisbon.id)
  Teacher.create(github_nickname: "mifig", school_id: lisbon.id)
  Teacher.create(github_nickname: "ZenKetse", school_id: lisbon.id)
  Teacher.create(github_nickname: "Ajguerra28", school_id: lisbon.id)
  Teacher.create(github_nickname: "louro-ines", school_id: lisbon.id)
  Teacher.create(github_nickname: "RyanDunsmuir", school_id: lisbon.id)
  Teacher.create(github_nickname: "volivers", school_id: lisbon.id)
  Teacher.create(github_nickname: "miguellutz", school_id: lisbon.id)
  Teacher.create(github_nickname: "gmrcp", school_id: lisbon.id)
  Teacher.create(github_nickname: "josh-merrill", school_id: lisbon.id)
  Teacher.create(github_nickname: "padilhaalucas", school_id: lisbon.id)
  Teacher.create(github_nickname: "anansilva", school_id: lisbon.id)
  Teacher.create(github_nickname: "AhmadMajid", school_id: lisbon.id)
  Teacher.create(github_nickname: "ricardosilva-rss", school_id: lisbon.id)
  Teacher.create(github_nickname: "raimundo-henriques", school_id: lisbon.id)
  Teacher.create(github_nickname: "gforgione", school_id: lisbon.id)
  Teacher.create(github_nickname: "joaquimvluis", school_id: lisbon.id)
  Teacher.create(github_nickname: "bakiewicz", school_id: lisbon.id)
  Teacher.create(github_nickname: "JoaoMartinsG", school_id: lisbon.id)

  puts "Creating DATA teachers..."
  Teacher.create(github_nickname: "mattrousseau", school_id: lisbon.id)
  Teacher.create(github_nickname: "vmoura56", school_id: lisbon.id)
  Teacher.create(github_nickname: "Michiel-DK", school_id: lisbon.id)
  Teacher.create(github_nickname: "qiweihan", school_id: lisbon.id)
  Teacher.create(github_nickname: "JoaoCalem", school_id: lisbon.id)
  Teacher.create(github_nickname: "alexisgourdol", school_id: lisbon.id)
  Teacher.create(github_nickname: "MargaridaMCampos", school_id: lisbon.id)
  Teacher.create(github_nickname: "EKULG", school_id: lisbon.id)
  Teacher.create(github_nickname: "Valentin-Laurent", school_id: lisbon.id)
  Teacher.create(github_nickname: "jdlourenco", school_id: lisbon.id)
  Teacher.create(github_nickname: "OlivierPaulo", school_id: lisbon.id)
  Teacher.create(github_nickname: "EduardoHidalgoGarcia", school_id: lisbon.id)
  Teacher.create(github_nickname: "thierry-silbermann", school_id: lisbon.id)
  Teacher.create(github_nickname: "emanuelfrazao", school_id: lisbon.id)
  Teacher.create(github_nickname: "archifreitas", school_id: lisbon.id)
  Teacher.create(github_nickname: "McNickSisto", school_id: lisbon.id)
  Teacher.create(github_nickname: "slbenfica1079", school_id: lisbon.id)
  Teacher.create(github_nickname: "gmatos51", school_id: lisbon.id)
  Teacher.create(github_nickname: "IolandaVelho", school_id: lisbon.id)
  Teacher.create(github_nickname: "joao-sr", school_id: lisbon.id)
  Teacher.create(github_nickname: "Phlasse", school_id: lisbon.id)
  Teacher.create(github_nickname: "tiagoyuhang", school_id: lisbon.id)
  Teacher.create(github_nickname: "kepler", school_id: lisbon.id)
  Teacher.create(github_nickname: "mlyngholm", school_id: lisbon.id)
  Teacher.create(github_nickname: "black-dalia", school_id: lisbon.id)
  Teacher.create(github_nickname: "isabel-fonseca", school_id: lisbon.id)
  Teacher.create(github_nickname: "ninadamaso", school_id: lisbon.id)
  Teacher.create(github_nickname: "MalouO", school_id: lisbon.id)
  Teacher.create(github_nickname: "AmElmo", school_id: lisbon.id)
  Teacher.create(github_nickname: "Tolugu", school_id: lisbon.id)
  Teacher.create(github_nickname: "SLShimizu", school_id: lisbon.id)
  Teacher.create(github_nickname: "IStege", school_id: lisbon.id)
  Teacher.create(github_nickname: "irlnicolas", school_id: lisbon.id)
  Teacher.create(github_nickname: "hugofborges", school_id: lisbon.id)
  Teacher.create(github_nickname: "sjoerdreyer", school_id: lisbon.id)
  Teacher.create(github_nickname: "Tara-Sophia", school_id: lisbon.id)

  puts "Teachers created!"
end
